### ISSUE TITLE
Unable to start the dashboard

### ISSUE THREAD

**Issue by sand7000** [Open-MBEE/mms5-layer0-dashboard#1]
Running on Ubuntu 20. Installation per the instructions results in an error:
```
$ npm i

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: mms5-dashboard@0.0.1
npm ERR! Found: vite@2.9.15
npm ERR! node_modules/vite
npm ERR!   dev vite@"^2.9.9" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^3.0.0" from @sveltejs/vite-plugin-svelte@1.0.2
npm ERR! node_modules/@sveltejs/vite-plugin-svelte
npm ERR!   @sveltejs/vite-plugin-svelte@"^1.0.0-next.44" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
The recommendation to try the force flag gets the install to complete but then I can't start it. Not sure if the issue is that I used the force flag or if there is a problem with vite.config.js:

```
$ npm run dev

> mms5-dashboard@0.0.1 dev
> vite --mode dev

failed to load config from /home/name/layer0/mms5-layer0-dashboard/vite.config.js
error when starting dev server:
/home/name/layer0/mms5-layer0-dashboard/node_modules/@sveltejs/vite-plugin-svelte/dist/index.cjs:542
        const _require = importMetaUrl ? esmRequire ?? (esmRequire = (0, import_module.createRequire)(importMetaUrl)) : require;
                                                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .js] (/home/name/layer0/mms5-layer0-dashboard/node_modules/vite/dist/node/chunks/dep-689425f3.js:62009:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/name/layer0/mms5-layer0-dashboard/vite.config.js:34:33)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
```

**Comment by sand7000** [comment]
Fiddling with versions in the package.json files didn't get me any further. Yarn was also failing to build until I ran:

nvm install 16.0.0

and then I was able to build and run the dashboard
